DROP TABLE CONTRIBUTOR CASCADE CONSTRAINTS PURGE


DROP TABLE CUSTOMER CASCADE CONSTRAINTS PURGE


DROP TABLE DISTRIBUTOR CASCADE CONSTRAINTS PURGE


DROP TABLE GENRE CASCADE CONSTRAINTS PURGE


DROP TABLE MOVIE CASCADE CONSTRAINTS PURGE


DROP TABLE MOVIEACTOR CASCADE CONSTRAINTS PURGE


DROP TABLE MOVIEDISTRIBUTOR CASCADE CONSTRAINTS PURGE


DROP TABLE MOVIEGENRE CASCADE CONSTRAINTS PURGE


DROP TABLE MOVIERENTED CASCADE CONSTRAINTS PURGE


DROP TABLE MOVIESONG CASCADE CONSTRAINTS PURGE


DROP TABLE RATING CASCADE CONSTRAINTS PURGE


DROP TABLE RENTALAGREEMENT CASCADE CONSTRAINTS PURGE


DROP TABLE SONG CASCADE CONSTRAINTS PURGE


DROP TABLE SONGAUTHOR CASCADE CONSTRAINTS PURGE


DROP TABLE SONGPERFORMER CASCADE CONSTRAINTS PURGE


DROP TABLE TABLESOURCEMASTER CASCADE CONSTRAINTS PURGE


DROP TABLE VALIDDURATION CASCADE CONSTRAINTS PURGE


DROP TABLE VOLUMEPROMOTION CASCADE CONSTRAINTS PURGE


DROP TABLE EBOOK CASCADE CONSTRAINTS PURGE


DROP TABLE BOOKAUTHOR CASCADE CONSTRAINTS PURGE


DROP TABLE BOOKRENTED CASCADE CONSTRAINTS PURGE